version: "1.0.0"

services:
  server:
    container_name: server
    restart: always
    build: .
    env_file: ./.env.prod
    environment: 
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
    ports: 
      - "9000:9000" 
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
   
    volumes:
      - ./data:/data/db
    env_file: ./.env.prod
    ports:
      - "27017:27017" 